export function MinimalPulseButton() {
	return (
		<div className="flex flex-col items-center gap-4 p-8 rounded-2xl bg-white/5 backdrop-blur-sm border border-white/10 hover:border-[#1cade4]/50 transition-all">
			<h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
				Minimal Pulse
			</h3>
			<button
				type="button"
				className="group relative px-8 py-4 rounded-md border border-[#1cade4]/30 hover:border-[#1cade4] hover:bg-[#1cade4]/10 transition-all duration-300"
			>
				<div className="absolute inset-0 rounded-md bg-[#1cade4]/20 animate-pulse opacity-0 group-hover:opacity-100" />
				<div className="relative flex items-center gap-3">
					<div className="relative flex items-center justify-center">
						<div className="absolute w-2 h-2 bg-[#1cade4] rounded-full animate-ping" />
						<div className="relative w-2 h-2 bg-[#1cade4] rounded-full" />
					</div>
					<span className="font-medium text-[#1cade4]">
						Generated by AI
					</span>
				</div>
			</button>
		</div>
	);
}
